openapi: 3.0.0
info:
  title: Forum API
  version: 1.0.0
  description: API для форума с чатом и авторизацией

servers:
  - url: http://localhost:8080
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
    
    Message:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        username:
          type: string
        created_at:
          type: string
          format: date-time
    
    Error:
      type: object
      properties:
        error:
          type: string

paths:
  /api/auth/register:
    post:
      summary: Регистрация нового пользователя
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Успешная регистрация
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/auth/login:
    post:
      summary: Авторизация пользователя
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Неверные учетные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /ws:
    get:
      summary: WebSocket подключение для чата
      tags:
        - chat
      security:
        - bearerAuth: []
      responses:
        '101':
          description: WebSocket подключение установлено
        '401':
          description: Требуется авторизация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 